version: 2.1

jobs:
  test_job:
    docker:
      - image: cimg/python:3.8  # Use the correct Python version
    steps:
      - checkout  # Pull down the source code
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install pytest  # Ensure pytest is installed
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest  # Run pytest to execute the tests
      - store_test_results:
          path: test-results

workflows:
  test_workflow:
    jobs:
      - test_job